db:
  application:
    user: ecny_app
    password: asupersecretpassword
    host: localhost
    port: 35432
    database: ecny
  migration:
    user: ecny_dba
    password: asupersecretpassword
    host: localhost
    port: 35432
    database: ecny